ops: update github workflows

diff --git a/.github/workflows/check_version.yml b/.github/workflows/check_version.yml
--- a/.github/workflows/check_version.yml
+++ b/.github/workflows/check_version.yml
@@ -5,43 +5,47 @@ on:
     branches:
       - main
     paths:
-      - 'py_package/setup.py'
+      - "pyproject.toml"
 
 jobs:
   check-version:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout PR branch
-      uses: actions/checkout@v4
-      with:
-        fetch-depth: 0
+      - name: Checkout PR branch
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
-    - name: Set up Python
-      uses: actions/setup-python@v4
-      with:
-        python-version: '3.x'
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: "3.x"
 
-    - name: Extract PR version
-      id: pr_version
-      run: |
-        PR_VERSION=$(grep -oP "version='\K[^']+" py_package/setup.py)
-        echo "pr_version=$PR_VERSION" >> $GITHUB_OUTPUT
-        echo "PR Version: $PR_VERSION"
+      - name: Install toml package
+        run: pip install toml
 
-    - name: Extract main version
-      id: main_version
-      run: |
-        git fetch origin main
-        MAIN_VERSION=$(git show origin/main:py_package/setup.py | grep -oP "version='\K[^']+")
-        echo "main_version=$MAIN_VERSION" >> $GITHUB_OUTPUT
-        echo "Main Version: $MAIN_VERSION"
+      - name: Extract PR version
+        id: pr_version
+        run: |
+          PR_VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
+          echo "pr_version=$PR_VERSION" >> $GITHUB_OUTPUT
+          echo "PR Version: $PR_VERSION"
 
-    - name: Compare versions
-      id: compare_versions
-      run: |
-        if [ "${{ steps.pr_version.outputs.pr_version }}" == "${{ steps.main_version.outputs.main_version }}" ]; then
-          echo "::error::Version in setup.py must be updated from '${{ steps.main_version.outputs.main_version }}' when making a PR to main branch"
-          exit 1
-        else
-          echo "Version was updated from '${{ steps.main_version.outputs.main_version }}' to '${{ steps.pr_version.outputs.pr_version }}'"
-        fi 
+      - name: Extract main version
+        id: main_version
+        run: |
+          git fetch origin main
+          git show origin/main:pyproject.toml > main_pyproject.toml
+          MAIN_VERSION=$(python -c "import toml; print(toml.load('main_pyproject.toml')['project']['version'])")
+          echo "main_version=$MAIN_VERSION" >> $GITHUB_OUTPUT
+          echo "Main Version: $MAIN_VERSION"
+
+      - name: Compare versions
+        id: compare_versions
+        run: |
+          if [ "${{ steps.pr_version.outputs.pr_version }}" == "${{ steps.main_version.outputs.main_version }}" ]; then
+            echo "::error::Version in pyproject.toml must be updated from '${{ steps.main_version.outputs.main_version }}' when making a PR to main branch"
+            exit 1
+          else
+            echo "Version was updated from '${{ steps.main_version.outputs.main_version }}' to '${{ steps.pr_version.outputs.pr_version }}'"
+          fi
